### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'enable_no_interaction'

### ISSUE THREAD

**Issue by lilong110112113** [JohnDreamer/HCCM#1]
Traceback (most recent call last):
  File "train_hc.py", line 281, in <module>
    train(opt)
  File "train_hc.py", line 92, in train
    lw_model = LossWrapper(model, opt)
  File "/home/z/HCCM-main/misc/loss_wrapper_hc.py", line 41, in __init__
    if opt.enable_no_interaction == 1:
AttributeError: 'Namespace' object has no attribute 'enable_no_interaction'
Terminating BlobFetcher

please help me,i can't solve it. Thank you.

**Comment by JohnDreamer** [comment]
Sorry for the late reply! The problem has been fixed.
